version: '3'

services:
  app:
    build: .
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db
    command: /app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8010

  db:
    image: mongo:4.4.3
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
